### PR TITLE
iOS fix: disable device name changing.

### PR DESCRIPTION
**Pull request by liuzjalex**
## What does this implement/fix? Explain your changes.
iOS fix: disable device name changing.

## Does this close any currently open issues?  
If it fixes a bug or resolves a feature request, be sure to link to that issue.
…

## Pull request type
 
_Put an `x` in the boxes that apply_
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
…

## Any other comments?
…

### CODE REVIEW

**Review by DevoutCoder — APPROVED** [review]

**Comment by danielsocials** [comment]
修改硬件名称为什么关掉？

**Comment by liuzjalex** [comment]
Python 没有修改的接口

**Comment by shuaiLiWang** [comment]
> Python 没有修改的接口

一直都有啊 修改硬件名称 只是apply_setting接口的一个参数而已 （label参数）

**Comment by liuzjalex** [comment]
> > Python 没有修改的接口
> 
> 一直都有啊 修改硬件名称 只是apply_setting接口的一个参数而已 （label参数）

好吧，目前暂时跟安卓同步，隐藏掉这个未实现的功能。

**Comment by liuzjalex** [comment]
这是一个 iOS 端没有完全实现的功能，这边暂时下掉。

**Pull request merged**
