### PR TITLE
Update get_client_by_chain

### PR DESCRIPTION
**Pull request by huazhouwang**
## What does this implement/fix? Explain your changes.
因为 App 可能会在熄屏状态调用 Python 服务，但此时可能某些问题（权限？）导致请求网络失败而错误把节点标记成不可用，所以加了个备份方案，返回第一个节点，保证可用性

## Does this close any currently open issues?  
If it fixes a bug or resolves a feature request, be sure to link to that issue.
…

## Pull request type
 
_Put an `x` in the boxes that apply_
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
…

## Any other comments?
…

### CODE REVIEW

**Review by liyanhrxy — DISMISSED** [review]

**Comment by taimanhui** [comment]
好神奇...

**Review by taimanhui — DISMISSED** [review]

**Comment by huazhouwang** [comment]
@taimanhui @liyanhrxy 你们觉得这么做可以不？我没想到好的方案

**Comment by huazhouwang** [comment]
@taimanhui @liyanhrxy 这种方式如何？首先去掉出错节点的 skip_seconds，然后优先从上次可用的节点处遍历一圈

**Review by liyanhrxy — APPROVED** [review]

**Review by taimanhui — APPROVED** [review]
应该没啥问题，就这样先试试吧

**Pull request merged**
